import type { OxlintConfig } from "oxlint";

export default {
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/anti-slop/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/test-results/**",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/anti-slop/index.ts" },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
  overrides: [
    {
      files: [
        "packages/nudge-ui/src/compiler/**",
        "packages/nudge-ui/src/hosts/vite/components/**",
        "packages/nudge-ui/src/hosts/vite/tokens/**",
        "packages/compatibility/src/playwright.ts",
        "packages/nudge-ui/src/inspector/canvas/frameProtocol.ts",
        "packages/nudge-ui/src/inspector/canvas/rendererBootstrap.ts",
        "packages/nudge-ui/src/inspector/canvas/rendererElementSelector.ts",
        "packages/nudge-ui/src/inspector/canvas/rendererStylesheet.ts",
        "packages/nudge-ui/src/inspector/canvas/sessionStore.ts",
        "packages/nudge-ui/src/inspector/componentSemantics/boundaries.ts",
        "packages/nudge-ui/src/inspector/componentSemantics/reactRuntime.tsx",
        "packages/nudge-ui/src/inspector/componentSemantics/runtimeTypes.ts",
        "packages/nudge-ui/src/inspector/inline-text/textChangeBoundary.ts",
        "packages/nudge-ui/src/inspector/projection/renderedInstance.ts",
        "packages/nudge-ui/src/inspector/projection/structuralProjectionBoundary.ts",
        "packages/nudge-ui/src/inspector/projection/textProjection.ts",
        "packages/nudge-ui/src/inspector/selection/resolveSelection.ts",
        "packages/nudge-ui/src/inspector/tokens/resolution/cssomCollector.ts",
        "packages/agent-protocol/src/index.ts",
        "packages/nudge-ui/src/hosts/next/wrapper.ts",
        "packages/mcp/src/bridge.ts",
        "packages/nudge-ui/src/inspector/agent/httpTransport.ts",
        "packages/nudge-ui/src/inspector/agent/verification.ts",
        "packages/nudge-ui/src/inspector/canvas/agentPresentation.ts",
        "packages/nudge-ui/src/inspector/prompt/clipboardHandoff.ts",
        "packages/nudge-ui/src/inspector/runtime/runtimeConfig.ts",
        "packages/nudge-ui/src/project/tokens.ts",
      ],
      rules: {
        "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-reflect-apply": "warn",
        "anti-slop/no-reflect-get": "warn",
        "anti-slop/no-unknown-parameters": "warn",
        "anti-slop/no-unknown-returns": "warn",
        "anti-slop/no-unsafe-dictionary-type": "warn",
        "anti-slop/require-safety-comment-for-type-assertion": "warn",
      },
    },
    {
      files: [
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/tests/**",
        "**/_testUtils.ts",
      ],
      rules: {
        "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-reflect-apply": "off",
        "anti-slop/no-reflect-get": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unknown-returns": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
      },
    },
  ],
} satisfies OxlintConfig;
