import type { OxlintConfig } from "oxlint";

export default {
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/anti-slop/**",
    "**/dist/**",
    "**/node_modules/**",
    "**/test-results/**",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
  overrides: [
    {
      files: [
        "packages/plugin/src/transform/**",
        "packages/plugin/src/components/**",
        "packages/plugin/src/adapters/**",
        "packages/plugin/src/tokens/**",
        "packages/compatibility/src/playwright.ts",
        "packages/inspector/src/canvas/frameProtocol.ts",
        "packages/inspector/src/canvas/rendererBootstrap.ts",
        "packages/inspector/src/canvas/rendererElementSelector.ts",
        "packages/inspector/src/canvas/rendererStylesheet.ts",
        "packages/inspector/src/canvas/sessionStore.ts",
        "packages/inspector/src/componentSemantics/boundaries.ts",
        "packages/inspector/src/componentSemantics/reactRuntime.tsx",
        "packages/inspector/src/componentSemantics/runtimeTypes.ts",
        "packages/inspector/src/renderedInstance.ts",
        "packages/inspector/src/resolveSelection.ts",
        "packages/inspector/src/structuralProjectionBoundary.ts",
        "packages/inspector/src/tokens/resolution/cssomCollector.ts",
      ],
      rules: {
          "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-reflect-apply": "warn",
        "anti-slop/no-reflect-get": "warn",
        "anti-slop/no-unknown-parameters": "warn",
        "anti-slop/no-unknown-returns": "warn",
        "anti-slop/no-unsafe-dictionary-type": "warn",
        "anti-slop/require-safety-comment-for-type-assertion": "warn",
      },
    },
    {
      files: [
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/tests/**",
        "**/_testUtils.ts",
      ],
      rules: {
        "anti-slop/no-chained-type-assertions": "warn",
        "anti-slop/no-reflect-apply": "off",
        "anti-slop/no-reflect-get": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unknown-returns": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
      },
    },
  ],
} satisfies OxlintConfig;
