import {
  type NudgeUiClientManifest,
  type NudgeUiRuntimeConfig,
} from "@nudge-ui/inspector/client-manifest";
import type { Plugin, ViteDevServer } from "vite";
import { createAstroRuntimeConfig } from "./astroRuntimeConfig.ts";
import { createAstroClientAssetHandler } from "./clientAsset.ts";

import {
  NUDGE_UI_CLIENT_PATH,
  NUDGE_UI_MANIFEST_PATH,
} from "nudge-ui/transport";

const serveClient = createAstroClientAssetHandler();

interface TokenModule {
  readonly nudgeUiProjectId: string;
  readonly tokenCatalog: NudgeUiRuntimeConfig["tokenCatalog"];
  readonly tokens: NudgeUiRuntimeConfig["tokens"];
  readonly tokenDiagnostics: NudgeUiRuntimeConfig["tokenDiagnostics"];
  readonly tokenGeneration: string;
}

interface ComponentModule {
  readonly componentContracts: NudgeUiRuntimeConfig["componentContracts"];
}

/** Serves the prebuilt client and its host-neutral manifest in Astro dev. */
export function createAstroClientTransportPlugin(): Plugin {
  return {
    name: "nudge-ui-astro-client-transport",
    // The shared Vite plugin exposes the same route for React hosts. Astro's
    // host-specific manifest must be installed first so that its middleware
    // is the handler that answers /__nudge_ui__/manifest.
    enforce: "pre",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const pathname = new URL(request.url ?? "/", "http://nudge-ui.local").pathname;
        if (pathname === NUDGE_UI_CLIENT_PATH) {
          void serveClient(request, response).catch(next);
          return;
        }
        if (pathname === NUDGE_UI_MANIFEST_PATH) {
          void createManifest(server)
            .then((manifest) => {
              response.statusCode = 200;
              response.setHeader("Content-Type", "application/json; charset=utf-8");
              response.setHeader("Cache-Control", "no-store");
              response.end(JSON.stringify(manifest));
            })
            .catch(next);
          return;
        }
        next();
      });
    },
  };
}

async function createManifest(
  server: ViteDevServer,
): Promise<NudgeUiClientManifest> {
  // SAFETY: these virtual modules are generated by the shared Nudge UI plugin
  // with the exact exports described by TokenModule and ComponentModule.
  const [tokenModule, componentModule] = await Promise.all([
    server.ssrLoadModule("virtual:design-tokens") as Promise<TokenModule>,
    server.ssrLoadModule("virtual:nudge-ui-components") as Promise<ComponentModule>,
  ]);
  return {
    version: 1,
    revision: 0,
    runtime: createAstroRuntimeConfig({
      projectId: tokenModule.nudgeUiProjectId,
      tokenCatalog: tokenModule.tokenCatalog,
      tokens: tokenModule.tokens,
      tokenDiagnostics: tokenModule.tokenDiagnostics,
      tokenGeneration: tokenModule.tokenGeneration,
      componentContracts: componentModule.componentContracts,
    }),
  };
}
