import { readFile } from "node:fs/promises";
import type { ServerResponse } from "node:http";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import type {
  NudgeUiClientManifest,
  NudgeUiRuntimeConfig,
} from "@nudge-ui/inspector/client-manifest";
import type { Plugin, ViteDevServer } from "vite";

export const ASTRO_ROUTE_PREFIX = "/__nudge_ui__/";
export const ASTRO_CLIENT_PATH = `${ASTRO_ROUTE_PREFIX}client.mjs`;
export const ASTRO_MANIFEST_PATH = `${ASTRO_ROUTE_PREFIX}manifest`;

const ASTRO_SCOPING_SELECTOR_PATTERN =
  "\\[data-astro-cid-[^\\]]*\\]|\\.astro-[a-zA-Z0-9_-]+";
const ASTRO_SOURCE_COORDINATES = {
  exactCidPrefixes: ["astro:"],
  exactFileExtensions: [".astro", ".html", ".htm"],
} as const;

interface TokenModule {
  readonly nudgeUiProjectId: string;
  readonly tokenCatalog: NudgeUiRuntimeConfig["tokenCatalog"];
  readonly tokens: NudgeUiRuntimeConfig["tokens"];
  readonly tokenDiagnostics: NudgeUiRuntimeConfig["tokenDiagnostics"];
  readonly tokenGeneration: string;
}

interface ComponentModule {
  readonly componentContracts: NudgeUiRuntimeConfig["componentContracts"];
}

/** Serves the prebuilt client and its host-neutral manifest in Astro dev. */
export function createAstroClientTransportPlugin(): Plugin {
  return {
    name: "nudge-ui-astro-client-transport",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const pathname = new URL(request.url ?? "/", "http://nudge-ui.local").pathname;
        if (pathname === ASTRO_CLIENT_PATH) {
          void serveClient(response).catch(next);
          return;
        }
        if (pathname === ASTRO_MANIFEST_PATH) {
          void createManifest(server, 0)
            .then((manifest) => {
              response.statusCode = 200;
              response.setHeader("Content-Type", "application/json; charset=utf-8");
              response.setHeader("Cache-Control", "no-store");
              response.end(JSON.stringify(manifest));
            })
            .catch(next);
          return;
        }
        next();
      });
    },
  };
}

async function serveClient(response: ServerResponse): Promise<void> {
  const body = await readFile(resolveInspectorClientPath());
  response.statusCode = 200;
  response.setHeader("Content-Type", "text/javascript; charset=utf-8");
  response.setHeader("Cache-Control", "no-cache");
  response.end(body);
}

async function createManifest(
  server: ViteDevServer,
  revision: number,
): Promise<NudgeUiClientManifest> {
  // SAFETY: these virtual modules are generated by the shared Nudge UI plugin
  // with the exact exports described by TokenModule and ComponentModule.
  const [tokenModule, componentModule] = await Promise.all([
    server.ssrLoadModule("virtual:design-tokens") as Promise<TokenModule>,
    server.ssrLoadModule("virtual:nudge-ui-components") as Promise<ComponentModule>,
  ]);
  const tokens = tokenModule.tokens;
  return {
    version: 1,
    revision,
    runtime: {
      projectId: tokenModule.nudgeUiProjectId,
      host: "astro",
      framework: "Astro",
      stylingSystem: detectStylingSystem(tokens),
      capabilities: {
        canvas: false,
        componentSemantics: true,
        sourceCoordinates: ASTRO_SOURCE_COORDINATES,
        scopingSelectorPattern: ASTRO_SCOPING_SELECTOR_PATTERN,
      },
      tokenCatalog: tokenModule.tokenCatalog,
      tokens,
      tokenDiagnostics: tokenModule.tokenDiagnostics,
      tokenGeneration: tokenModule.tokenGeneration,
      componentContracts: componentModule.componentContracts,
    },
  };
}

function resolveInspectorClientPath(): string {
  if (import.meta.url.endsWith(".ts")) {
    return fileURLToPath(new URL("../../inspector/dist/client.mjs", import.meta.url));
  }
  return createRequire(import.meta.url).resolve("@nudge-ui/inspector/client");
}

function detectStylingSystem(tokens: NudgeUiRuntimeConfig["tokens"]): string {
  for (const token of tokens) {
    const adapter = token.adapter;
    if (adapter === "vanilla-extract") return "vanilla-extract (sprinkles)";
    if (adapter === "tailwind-v3") return "Tailwind v3";
    if (adapter === "tailwind-v4") return "Tailwind v4";
  }
  return "CSS custom properties";
}
