import {
  type NudgeUiClientManifest,
  type NudgeUiRuntimeConfig,
} from "../../inspector/clientManifest.ts";
import type { Plugin, ViteDevServer } from "vite";
import type { IncomingMessage } from "node:http";
import { createAstroRuntimeConfig } from "./astroRuntimeConfig.ts";
import { createAstroClientAssetHandler } from "./clientAsset.ts";

import {
  NUDGE_UI_CLIENT_PATH,
  NUDGE_UI_EDITOR_PATH,
  NUDGE_UI_MANIFEST_PATH,
  createNudgeUiEditorDocument,
  isNudgeUiEditorDocumentRequest,
} from "../../transport/index.ts";
import { startOptionalProjectBridge } from "../projectBridge.ts";
import { automationManifestFields } from "../environment.ts";

const serveClient = createAstroClientAssetHandler();

interface TokenModule {
  readonly nudgeUiProjectId: string;
  readonly tokenCatalog: NudgeUiRuntimeConfig["tokenCatalog"];
  readonly tokens: NudgeUiRuntimeConfig["tokens"];
  readonly tokenDiagnostics: NudgeUiRuntimeConfig["tokenDiagnostics"];
  readonly tokenGeneration: string;
}

interface ComponentModule {
  readonly componentContracts: NudgeUiRuntimeConfig["componentContracts"];
}

/** Serves the prebuilt client and its host-neutral manifest in Astro dev. */
export function createAstroClientTransportPlugin(): Plugin {
  let projectBridge: Awaited<ReturnType<typeof startOptionalProjectBridge>> = null;
  return {
    name: "nudge-ui-astro-client-transport",
    // The shared Vite plugin exposes the same route for React hosts. Astro's
    // host-specific manifest must be installed first so that its middleware
    // is the handler that answers /__nudge_ui__/manifest.
    enforce: "pre",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const pathname = new URL(request.url ?? "/", "http://nudge-ui.local").pathname;
        if (isNudgeUiEditorDocumentRequest(request.url ?? "/", request.method, request.headers)) {
          if (request.method !== "GET" && request.method !== "HEAD") {
            response.statusCode = 405;
            response.setHeader("Allow", "GET, HEAD");
            response.end();
            return;
          }
          response.statusCode = 200;
          response.setHeader("Content-Type", "text/html; charset=utf-8");
          response.setHeader("Cache-Control", "no-store");
          response.end(request.method === "HEAD" ? undefined : createNudgeUiEditorDocument());
          return;
        }
        if (pathname === NUDGE_UI_CLIENT_PATH) {
          void serveClient(request, response).catch(next);
          return;
        }
        if (pathname === NUDGE_UI_MANIFEST_PATH) {
          void createManifest(server, request, (bridge) => {
            projectBridge = bridge;
          })
            .then((manifest) => {
              response.statusCode = 200;
              response.setHeader("Content-Type", "application/json; charset=utf-8");
              response.setHeader("Cache-Control", "no-store");
              response.end(JSON.stringify(manifest));
            })
            .catch(next);
          return;
        }
        next();
      });
    },
    async closeBundle() {
      await projectBridge?.close();
      projectBridge = null;
    },
  };
}

async function createManifest(
  server: ViteDevServer,
  request: IncomingMessage,
  setBridge: (bridge: Awaited<ReturnType<typeof startOptionalProjectBridge>>) => void,
): Promise<NudgeUiClientManifest> {
  // SAFETY: these virtual modules are generated by the shared Nudge UI plugin
  // with the exact exports described by TokenModule and ComponentModule.
  const [tokenModule, componentModule] = await Promise.all([
    server.ssrLoadModule("virtual:design-tokens") as Promise<TokenModule>,
    server.ssrLoadModule("virtual:nudge-ui-components") as Promise<ComponentModule>,
  ]);
  const runtime = createAstroRuntimeConfig({
    projectId: tokenModule.nudgeUiProjectId,
    tokenCatalog: tokenModule.tokenCatalog,
    tokens: tokenModule.tokens,
    tokenDiagnostics: tokenModule.tokenDiagnostics,
    tokenGeneration: tokenModule.tokenGeneration,
    componentContracts: componentModule.componentContracts,
  });
  const origin = resolvedRequestOrigin(server, request);
  const bridge = origin
    ? await startOptionalProjectBridge({
      appRoot: server.config.root,
      projectId: runtime.projectId,
      origin,
      info: (message) => server.config.logger.info(message),
      warn: (message) => server.config.logger.warn(message),
    })
    : null;
  setBridge(bridge);
  return {
    version: 1,
    revision: 0,
    runtime,
    ...(bridge ? { agentBridge: bridge.browser } : {}),
    ...automationManifestFields(),
  };
}

function resolvedRequestOrigin(server: ViteDevServer, request: IncomingMessage): string | null {
  const host = request.headers.host;
  if (!host) return null;
  const candidates = [
    ...(server.resolvedUrls?.local ?? []),
    ...(server.resolvedUrls?.network ?? []),
  ].map((url) => new URL(url).origin);
  const protocols = new Set(candidates.map((candidate) => new URL(candidate).protocol));
  for (const protocol of protocols) {
    const requested = new URL(`${protocol}//${host}`).origin;
    if (candidates.includes(requested)) return requested;
  }
  return null;
}
